# Fallback Config for codepipeline-watch
stack-name: the-codepipeline-watch
github:
  token: token-to--be-defined
slack: 
  token: token-to-be-defined
  channel: chanel-to-be-defined
dynamodb:
  table: codepipeline-watch-events
  capacity:
    read: 5
    write: 5
  autoscaling:
    target: 80
    scale-cooldown: 60
    min: 5
    max: 25
