# Fallback Config for codepipeline-watch
stack-name: the-codepipeline-watch
github:
  token: token-to--be-defined
slack: 
  token: token-to-be-defined
  channel: chanel-to-be-defined
dynamodb:
  table: codepipeline-watch-events
