# Fallback Config for codepipeline-watch
aws:
  stackName: codepipeline-watch-${opt:stage, 'production'}
  lambdaName: codepipeline-watch
  eventName: CodepipelineWatchCloudwatchEventTrigger
  scalingRoleName: CodepipelineWatchDynamodbScalingRoleFor${self:provider.region}
  lambdaRoleName: CodepipelineWatchAccessRoleFor${self:provider.region}
github:
  token: token-to--be-defined
slack:
  token: token-to-be-defined
  channel: chanel-to-be-defined
dynamodb:
  table: codepipeline-watch-events
  capacity:
    read: 5
    write: 5
  autoscaling:
    target: 80
    scale-cooldown: 60
    min: 5
    max: 25
